In [2]:
import numpy as np

In [1]:
dataset_root_path = "../fsx/a2d2/"
scene_id = "20180807_145028"
file_scene_prefix = scene_id.replace("_", "")
frame_id = "000000091"

input_1_location = f"../fsx/a2d2/camera_lidar_semantic_bboxes/{scene_id}/lidar/cam_front_center/{file_scene_prefix}_lidar_frontcenter_{frame_id}.bin"
print(input_1_location)

../fsx/a2d2/camera_lidar_semantic_bboxes/20180807_145028/lidar/cam_front_center/20180807145028_lidar_frontcenter_000000091.bin


In [3]:
points = np.fromfile(input_1_location, dtype=np.float32)

In [5]:
points.shape

(37044,)

In [9]:
load_dim = 4
points = points.reshape(-1, load_dim)

In [10]:
points.shape

(9261, 4)

In [11]:
points

array([[  6.0503883,   0.9620881,  -1.7177452,   7.       ],
       [  6.6677694,   1.1342102,  -1.7090718,   8.       ],
       [  7.4370627,   1.344765 ,  -1.7040207,   6.       ],
       ...,
       [ 34.2063   , -19.080511 ,   9.1748085,  73.       ],
       [ 34.216587 , -19.328083 ,   7.709195 ,  73.       ],
       [ 34.20591  , -19.241108 ,   9.199645 ,  73.       ]],
      dtype=float32)

In [12]:
lidar_front_center = np.load(input_1_location.replace('.bin', '.npz'))

In [15]:
print(list(lidar_front_center.keys()))

['azimuth', 'row', 'lidar_id', 'depth', 'reflectance', 'col', 'points', 'timestamp', 'distance']


In [22]:
for key in list(lidar_front_center.keys()):
    print(key, lidar_front_center[key].shape, lidar_front_center[key].dtype)

azimuth (9261,) float64
row (9261,) float64
lidar_id (9261,) float64
depth (9261,) float64
reflectance (9261,) int64
col (9261,) float64
points (9261, 3) float64
timestamp (9261,) int64
distance (9261,) float64


In [16]:
lidar_front_center['points']

array([[  6.05038855,   0.9620881 ,  -1.71774515],
       [  6.66776922,   1.13421021,  -1.70907173],
       [  7.4370629 ,   1.34476496,  -1.70402073],
       ...,
       [ 34.20629763, -19.08051037,   9.17480813],
       [ 34.21658837, -19.32808217,   7.70919526],
       [ 34.20591006, -19.24110816,   9.19964478]])

In [17]:
lidar_front_center['reflectance']

array([ 7,  8,  6, ..., 73, 73, 73])